<a href="https://colab.research.google.com/github/sakunisgithub/machine_learning/blob/master/NumPy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [4]:
# method 1
a = np.zeros(10); a[4] = 1
print(a)

1

In [ ]:
# method 2
a = np.eye(1, 10, k = 4).flatten()
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
a = int(input("Enter a = "))
b = int(input("Enter b = "))

arr1 = np.random.random((a, b))
print(arr1)

print(np.mean(arr1))

Enter a = 3
Enter b = 4
[[0.77376976 0.56050091 0.28349676 0.50771272]
 [0.56028105 0.6305824  0.5968936  0.22258679]
 [0.9724087  0.07936356 0.53864775 0.26561763]]
0.4993218003995023


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
def create_2d_array(a, b) :
  zero_array = np.zeros((a, b))
  b1 = np.ones(a)
  b2 = np.ones(b)

  zero_array[[0, a-1], :] = b2
  zero_array[:, 0] = b1.T
  zero_array[:, b-1] = b1.T
  return(zero_array)

print(create_2d_array(4, 4))
print(create_2d_array(5, 7))

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
a = np.random.random(10)
print(a)

[0.94780552 0.11561193 0.35404773 0.63735777 0.75105964 0.59527311
 0.3737999  0.72704774 0.02992816 0.51925294]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
# no

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
a = np.random.randint(0, 5, 25).reshape(5, 5)
print(a)

[[2 4 1 4 0]
 [0 1 1 3 1]
 [0 0 4 2 1]
 [0 2 0 4 1]
 [3 1 3 3 4]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vector from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
points = np.random.randint(1, 101, 20).reshape(10, 2)
print(points)

distance = np.empty((10,), dtype = np.int64)

point = np.array([2, 3])

for i in range(10):
  distance[i] = np.sqrt((point[0] - points[i, 0])**2 + (point[1] - points[i, 1])**2)

print(distance)

[[91 27]
 [65 26]
 [16 55]
 [84 93]
 [78 79]
 [89 60]
 [46 95]
 [ 8 88]
 [76 58]
 [18 78]]
[ 92  67  53 121 107 104 101  85  92  76]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
# (1, 5, 3)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
numbers = input().strip().split(' ')
numbers = [float(num) for num in numbers]

print(numbers[::-1])

1 2 3 4 -8 -10
[-10.0, -8.0, 4.0, 3.0, 2.0, 1.0]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
a = np.random.random(50)

print(np.size(a))

a = np.random.random(0)

print(np.size(a))

50
0


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [8]:
def softmax(arr):
  if arr.ndim != 1:
    raise ValueError("Input must be a 1D array.")

  return(np.exp(arr) / np.sum(np.exp(arr)))

a = np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318])
print(softmax(a))

b = np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278])
print(softmax(b))

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]
[4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [19]:
def vertical_stack(*args):
  for array in args:
    if not isinstance(array, np.ndarray):
      raise TypeError(f"All inputs must be NumPy arrays. Found: {type(array)}")

  return(np.vstack(args))

a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

vertical_stack(a, b)

c = np.array([[0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695], [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

vertical_stack(a, b, c)

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.10117373, 0.1677244 , 0.73764059, 0.83166097, 0.48985695],
       [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from same month and same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [52]:
def date_array(start, end):
  if not isinstance(start, str) or not isinstance(end , str) :
    raise TypeError("All the inputs must be strings.")

  dates = np.arange(int(start[-2:]), int(end[-2:]) + 1)

  output = []

  for i in range(len(dates)):
    output.append(start[0:8] + str(dates[i]))

  return(output)

print(date_array(start = '2022-12-01', end = '2022-12-06'))

print(date_array(start = '2020-11-25', end = '2020-11-30'))

['2022-12-1', '2022-12-2', '2022-12-3', '2022-12-4', '2022-12-5', '2022-12-6']
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28', '2020-11-29', '2020-11-30']


###`Q-14:` Subtract the mean of each row from corresponding row of a matrix.

In [55]:
mat = np.random.randint(0, 100, 24).reshape(6, 4)
print(mat)

rowmeans = np.mean(mat, axis = 1)
print(rowmeans)

for i in range(mat.shape[0]) :
  mat[i] = mat[i] - rowmeans[i]

print(mat)

[[46 72 34 96]
 [45 82 44 10]
 [43 88 26 82]
 [86 83 78 41]
 [28 42 19 77]
 [26 56 15  2]]
[62.   45.25 59.75 72.   41.5  24.75]
[[-16  10 -28  34]
 [  0  36  -1 -35]
 [-16  28 -33  22]
 [ 14  11   6 -31]
 [-13   0 -22  35]
 [  1  31  -9 -22]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [56]:
a = np.arange(12).reshape(3, 4)
print(a)

a[:, [0, 1]] = a[:, [1, 0]]

print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]


###`Q-16:` Replace odd elements in arrays with -1.

In [57]:
a = np.random.randint(0, 20, 10)
print(a)

a = np.where(a % 2 != 0, -1, a)
print(a)

[11 18  1 11  5  2  3  9 13  4]
[-1 18 -1 -1 -1  2 -1 -1 -1  4]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [61]:
def max_array(arr1, arr2) :
  stacked = np.vstack([arr1, arr2])
  return(np.max(stacked, axis = 0))

a = np.array([6,3,1,5,8])
b = np.array([3,2,1,7,2])

print(max_array(a, b))

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different forms of normalisation; for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [62]:
# Given
arr1 = np.random.randint(low = 1, high = 10000, size = 40).reshape(8,5)
arr1

array([[9276, 6672,  329, 6541, 5600],
       [9753, 1950, 8248, 4802, 4161],
       [7660, 7554, 3742, 5391, 3200],
       [9007, 1805,  257, 9075, 6040],
       [8370, 8349, 2318, 6794, 5305],
       [8408, 7660, 6796, 5238, 5007],
       [8208, 2334, 8377, 8861, 6763],
       [3154, 7732, 8947, 5095, 8801]])

In [66]:
print(arr1[:, 0:5:2])

[[9276  329 5600]
 [9753 8248 4161]
 [7660 3742 3200]
 [9007  257 6040]
 [8370 2318 5305]
 [8408 6796 5007]
 [8208 8377 6763]
 [3154 8947 8801]]


In [67]:
print((arr1 - np.min(arr1)) / (np.max(arr1) - np.min(arr1)))

[[0.94976832 0.6755476  0.00758214 0.66175232 0.56265796]
 [1.         0.17828559 0.84151222 0.47862258 0.41112047]
 [0.77959141 0.76842881 0.36699663 0.54064869 0.30991997]
 [0.92144061 0.16301601 0.         0.92860152 0.60899326]
 [0.85435973 0.85214827 0.21703875 0.68839511 0.53159225]
 [0.85836142 0.77959141 0.68860573 0.52453665 0.50021061]
 [0.83729992 0.21872367 0.85509688 0.90606571 0.68513058]
 [0.30507582 0.78717355 0.91512216 0.50947767 0.89974726]]


###`Q-19:` Write a function which will accept 2 arguments - (1) 1D numpy array arr (2) an integer n {Please make sure n<=len(arr)} and the output should be the nth largest item out of the array.
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [70]:
def my_func(arr, n):
  if n > len(arr) :
    raise ValueError("n must be less than or equal to the length of the given array.")

  return(-np.sort(-arr)[n-1])

arr = np.array([12, 34, 40, 7, 1, 0])

print(my_func(arr, 3))

print(my_func(arr, 1))

12
40


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [88]:
a = np.array([1,2,3])

a1 = np.vstack([a, a, a])
a2 = a1.T

print(np.append(a2.flatten(), a1.flatten()))

[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
