<a href="https://colab.research.google.com/github/sakunisgithub/machine_learning/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

$$\textbf{NumPy - Numerical Python}$$

### Creating NumPy arrays

In [ ]:
import numpy as np

In [ ]:
# 1D (a vector)
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
# 2D (a matrix)
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D (a tensor)
c = np.array([[[5, 6], [15, 16]], [[1, 2], [11, 12]]])
print(c)

[[[ 5  6]
  [15 16]]

 [[ 1  2]
  [11 12]]]


In [ ]:
## creating a numpy array of a particular data type

# float
a1 = np.array([1, 2, 3], dtype = float)
print(a1)

# boolean
a2 = np.array([0, 1, 2, 3], dtype = bool)
print(a2)

# complex
a3 = np.array([5, 7, 10], dtype = complex)
print(a3)

[ 5.+0.j  7.+0.j 10.+0.j]


In [ ]:
# by using arange() function - arange() is similar to range()
a4 = np.arange(1, 11)
print(a4) # np.arange(a, b) yields integers from a to b-1

a5 = np.arange(1, 11, 3)
print(a5)

arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [ ]:
# reshape() function
a6 = np.arange(1, 51).reshape(10, 5)
print(a6)

a7 = np.arange(1, 28).reshape(3, 3, 3)
print(a7)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [ ]:
# ones()
a8 = np.ones((5, 2)) # creates an array of shape (5, 2) with all the elements being 1
print(a8)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
a9 = np.ones((3, 4), dtype = int)
print(a9)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
# zeros()
a10 = np.zeros((2, 3)) # creates an array of shape (2, 3) with all the elements being 0
print(a10)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# random()
a11 = np.random.random((2, 3)) # creates an array of shape(2, 3) with all the elements being random numbers in between 0 and 1
print(a11)

[[0.56328291 0.37959647 0.33962274]
 [0.32288683 0.29169319 0.86256795]]


np.ones(), np.zeros(), np.random.random() are mainly useful in array initialization.

In [ ]:
# linspace() linearly spaced
a12 = np.linspace(-20, 20, 15) # generates 15 equispaced numbers from -20 to 20
print(a12)

[-20.         -17.14285714 -14.28571429 -11.42857143  -8.57142857
  -5.71428571  -2.85714286   0.           2.85714286   5.71428571
   8.57142857  11.42857143  14.28571429  17.14285714  20.        ]


In [ ]:
# identity()
a13 = np.identity(4) # creates an identity matrix of order 4
print(a13)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Array Attributes

In [ ]:
arr1 = np.arange(0, 11)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr2 = np.arange(1, 13, dtype = float).reshape(3, 4)
print(arr2)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [ ]:
arr3 = np.arange(8, dtype = np.int32).reshape(2, 2, 2)
print(arr3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# ndim - gives number of dimension(s) of an array
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [ ]:
# shape - gives dimension of an array
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(11,)
(3, 4)
(2, 2, 2)


In [ ]:
# size - gives number of elements in an object
print(arr2.size)
print(arr3.size)

12
8


In [ ]:
# itemsize - refers to the number of bytes used to store a single element of an array
print(arr1.itemsize)
print(arr2.itemsize)
print(arr3.itemsize)
# recall that 8 bits = 1 byte
# by default colab uses 64-bit integers and they take 8 bytes of space
# also floates in colab take 8 bytes of space
# 32-bit integers take 4 bytes of space

8
8
4


In [ ]:
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
float64
int32


### Changing datatype

In [ ]:
print(arr1.dtype)

int64


In [ ]:
arr1 = arr1.astype(np.int32)

In [ ]:
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(arr1.dtype)

int32


### Array Operations

In [ ]:
b1 = np.arange(1, 13).reshape(3, 4)
print(b1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
b2 = np.arange(13, 25).reshape(3, 4)
print(b2)

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
# scalar operation - operating in an array with a scalar
print(b1 + 2)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [ ]:
print(b1 * 2)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [ ]:
print(b1 / 2) # in division output datatype is always float

[[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [4.5 5.  5.5 6. ]]


In [ ]:
print(b1 ** 2)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [ ]:
# relational operation
print(b1 > 5)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [ ]:
print(b1 == 7)

[[False False False False]
 [False False  True False]
 [False False False False]]


In [ ]:
print(b1 != 3)

[[ True  True False  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
# vector operations
print(b1 + b2) # itemwise addition

[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]


In [ ]:
print(b1 * b2) # itemwise multiplication

[[ 13  28  45  64]
 [ 85 108 133 160]
 [189 220 253 288]]


### Common Array Functions