<a href="https://colab.research.google.com/github/sakunisgithub/machine_learning/blob/master/Deep%20Learning%20-%20IIT%20Ropar/week_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Q4

In [1]:
import numpy as np

In [2]:
mat = np.array([-4, -6, 3, -8]).reshape(2, 2)
print(mat)

[[-4 -6]
 [ 3 -8]]


In [3]:
a = np.dot(mat.T, mat)
print(a)

[[ 25   0]
 [  0 100]]


In [4]:
eigenvalues = np.linalg.eig(a)[0] # eigenvalues of a
print(eigenvalues)

[ 25. 100.]


In [5]:
print(np.sqrt(eigenvalues))

[ 5. 10.]


In [7]:
print(np.sqrt(np.diag(eigenvalues)))

[[ 5.  0.]
 [ 0. 10.]]


### Q6-Q9

In [9]:
x1 = np.array([-2, 2]).reshape(1, 2)
x2 = np.array([2, -2]).reshape(1, 2)
x3 = np.array([1, 1]).reshape(1, 2)

X = np.vstack([x1, x2, x3])
print(X)

[[-2  2]
 [ 2 -2]
 [ 1  1]]


In [10]:
print(np.mean(X, axis = 0))

[0.33333333 0.33333333]


In [18]:
print(np.cov(X.T))

[[ 4.33333333 -3.66666667]
 [-3.66666667  4.33333333]]


In [20]:
C = np.dot( (X - np.mean(X, axis = 0)).T, (X - np.mean(X, axis = 0))) / X.shape[0]

In [21]:
print(C)

[[ 2.88888889 -2.44444444]
 [-2.44444444  2.88888889]]


In [22]:
eigenvalues, eigenvectors = np.linalg.eig(C)

In [23]:
print(eigenvalues)

[5.33333333 0.44444444]


In [24]:
print(eigenvectors)

[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [25]:
print(np.max(eigenvalues))

5.333333333333334


In [28]:
print(eigenvectors[:, np.argmax(eigenvalues)])

[ 0.70710678 -0.70710678]
