<a href="https://colab.research.google.com/github/sakunisgithub/machine_learning/blob/master/Deep%20Learning%20-%20IIT%20Ropar/week_3_assignment_Q9_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 1]).T
x

array([1, 2, 1])

In [3]:
W_1 = np.array([[1, 1, 3], [2, -1, 1], [1, 2, -2]])
W_1

array([[ 1,  1,  3],
       [ 2, -1,  1],
       [ 1,  2, -2]])

In [4]:
a_1 = np.dot(W_1, x)
a_1

array([6, 1, 3])

In [5]:
def sigmoid(x):
  return(1/(1 + np.exp(-x)))

In [6]:
h_1 = sigmoid(a_1)
h_1

array([0.99752738, 0.73105858, 0.95257413])

In [7]:
W_2 = np.array([[1, 1, 2], [3, 1, 1]])
W_2

array([[1, 1, 2],
       [3, 1, 1]])

In [8]:
a_2 = np.dot(W_2, h_1)
a_2

array([3.63373421, 4.67621484])

In [9]:
h_2 = sigmoid(a_2)
h_2

array([0.97426256, 0.99077175])

In [10]:
W_3 = np.array([1, 2])
W_3

array([1, 2])

In [11]:
a_3 = np.dot(W_3, h_2)
a_3

2.955806064370453

In [13]:
(a_3 - 5) ** 2

4.178728846464617